server:
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.jks
    key-store-password: changeit
    key-alias: localhost
    key-password: changeit

    trust-store: truststore.jks
    trust-store-password: changeit

    client-auth: need
